version: '3.7'

services:
  mysql:  
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_password
      - MYSQL_DATABASE=pruebatecnica
      - MYSQL_USER=pruebatecnica
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    restart: unless-stopped
    networks:
        - default
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    secrets:
      - db_password

  pruebatecnica:
    build: .
    container_name: pruebatecnica
    hostname: pruebatecnica
    restart: unless-stopped
    volumes:
      - ../:/var/www/html:rw
    networks:
        - default
    depends_on:
      - mysql
    environment:
        LUMEN_APP_NAME: PruebaTécnica
        LUMEN_APP_ENV: local
        LUMEN_APP_DEBUG: 'false'
        LUMEN_APP_URL: http://localhost:8202
        LUMEN_DB_HOST: mysql
        LUMEN_DB_DATABASE: pruebatecnica
        LUMEN_DB_USERNAME: pruebatecnica
        LUMEN_DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
  nginx:
    image: nginx:1.17
    container_name: nginx
    depends_on:
        - pruebatecnica
    restart: unless-stopped
    networks:
        - default
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
        - ./nginx/nginxconfig.io:/etc/nginx/nginxconfig.io:ro
        - ../:/var/www/html:ro
    ports:
        - "8202:8202"
secrets:
  db_password:
    file: db_password.txt

volumes:
  mysql-data:

networks:
  default: